### ISSUE TITLE
Is this second lagged update to x_k a bug? I don't see it in the algorithm

### ISSUE THREAD

**Issue by NikZak** [adefazio/point-saga#2]
Forgive my lack of understanding. Could you please clarify this step? Why it happens two times?
https://github.com/adefazio/point-saga/blob/63597c67aa9a18f7d2d4ae12ef4c7230e3db3872/optimization/saga.pyx#L141

**Comment by adefazio** [comment]
So I wrote the code a long time ago so my memory is hazy, but I believe I'm using the lagged_update function for two purposes. This 2nd application of it performs a single step of the regularizer, i.e. the regular non-lagged application after the main step.

**Comment by NikZak** [comment]
Sorry, my bad.
